services:
  loki:
    image: grafana/loki:${LOKI_VERSION}
    command: -config.file=/etc/loki/config.yaml
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
      - ./loki/rules:/tmp/loki/rules:ro
      - loki-data:/loki
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-health"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:${PROM_VERSION}
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus/targets/hosts.yaml:/etc/prometheus/targets/hosts.yaml
      - prom-data:/prometheus
    ports: ["9090:9090"]
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:${AM_VERSION}
    command: --config.file=/etc/alertmanager/alertmanager.yaml
    volumes:
      - ./alertmanager/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml:ro
      - am-data:/alertmanager
    ports: ["9093:9093"]
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter:${BB_VERSION}
    command: --config.file=/etc/blackbox/blackbox.yaml
    volumes:
      - ./blackbox/blackbox.yaml:/etc/blackbox/blackbox.yaml:ro
    cap_add: [NET_RAW]
    restart: unless-stopped

  troubleshooter:
    build: troubleshooter/.
    ports: ["8080:8080"]
    env_file: .env
    depends_on:
      loki: { condition: service_healthy }
      prometheus: { condition: service_started }
    restart: unless-stopped

volumes:
  loki-data:
  prom-data:
  am-data:
