[project]
name = "trblsh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Anton Petrov", email = "a.petrov.83@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "httpx",
    "uvicorn",
    "asyncssh",
    "requests",
    "jinja2",
    "sqlmodel>=0.0.42",
    "python-dotenv>=1.2.3",
    "openai-agents>=0.22.1",
    "tzdata>=2026.3",
]
