groups:
  - name: availability
    rules:
      - alert: NodeExporterDown
        expr: up{job="node"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "node_exporter down on {{ $labels.instance }}"
          description: "Prometheus cannot scrape {{ $labels.instance }} for more than 1 minute."

      - alert: HostUnreachable
        expr: probe_success{job="blackbox-icmp"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "{{ $labels.instance }} does not respond to ping"

      - alert: SSHDown
        expr: probe_success{job="probe_ssh"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "SSH not reachable on {{ $labels.instance }}"
